host: "localhost:3000"
google_client_id: <%= Rails.application.credentials.google[:client_id] %>
google_client_secret: <%= Rails.application.credentials.google[:client_secret] %>
google_login_uri: <%= Rails.application.credentials.google[:login_uri] %>
google_api_key: <%= Rails.application.credentials.google[:api_key] %>